export const CHANGE_AMOUNT = "CHANGE_AMOUNT";
export const CHANGE_CHECK = "CHANGE_CHECK";
export const CHANGE_DATE = "CHANGE_DATE";
export const CHOOSE_TARGET = "CHOOSE_TARGET";
export const CHOOSE_SOURCE = "CHOOSE_SOURCE";
export const REMOVE_TARGET = "REMOVE_TARGET";

export const FETCH_LATEST_DATA_STARTED = "FETCH_LATEST_DATA_STARTED";
export const FETCH_LATEST_DATA_SUCCEEDED = "FETCH_LATEST_DATA_SUCCEEDED";
export const FETCH_LATEST_DATA_FINISHED = "FETCH_LATEST_DATA_FINISHED";
export const FETCH_LATEST_DATA_FAILED = "FETCH_LATEST_DATA_FAILED";

export const FETCH_HISTORICAL_DATA_STARTED = "FETCH_HISTORICAL_DATA_STARTED";
export const FETCH_HISTORICAL_DATA_SUCCEEDED = "FETCH_HISTORICAL_DATA_SUCCEEDED";
export const FETCH_HISTORICAL_DATA_FINISHED = "FETCH_HISTORICAL_DATA_FINISHED";
export const FETCH_HISTORICAL_DATA_FAILED = "FETCH_HISTORICAL_DATA_FAILED";

// Sagas
export const SUBMIT_REQUESTED = "SUBMIT_REQUESTED";
export const CHANGE_CHECK_REQUESTED = "CHANGE_CHECK_REQUESTED";
